version: "3"
services:
  teq:
    platform: linux/amd64
    container_name: login
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - example:/var/lib/postgresql/data
#    command:
#      [
#        "--default-authentication-plugin=mysql_native_password"
#      ]
volumes:
  example:
