name: GitHub Actions Demo
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-lastest
    services:
      postgres:
        image: postgres
        env:
          PO`STGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "data run"
      - name: Connect to PostgreSQL
        run: postgresql

