

name: GitHub Actions Demo
on: [push]
env:
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: login_db
  DB_USER: postgres
  DB_PASS: password
  DB_MAX_IDLE_CONNS: 10
  DB_MAX_OPEN_CONNS: 40
  DB_TX_RETRY_COUNT: 1
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: login_db
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: ls -a
      - uses: actions/setup-go@v3
      - run: go version
      - run: echo $GOROOT
#      - run: cd backend && go mod download
      - run: cd backend && go run ./cmd/migrate.go

